### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by moki** [dimaip/server-side-rendering#2]
I wonder if u meant /build instead of /built

```
output: {
    path: path.join(__dirname, 'built/'),
    filename: 'index.js',
    publicPath: '/built/'
  },
```

**Comment by KSMorozov** [comment]
nm after digging into tutorial realized that naming is intentional 😅

**Comment by dimaip** [comment]
Yeah it's written in the past tense to reflect that it contains build artifacts, and not build scripts or anything.
